-- Exercise SQL01-EX-04
CREATE TABLE HR.EMP AS (
    SELECT *
    FROM HR.EMPLOYEES
);

INSERT INTO HR.EMP (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY)
VALUES (
    250, 'Erman', 'İbrisim', 'erman@ibrisim', 5556783245,
    TO_DATE('17-JUN-03'),
    'IT_PROG', 15000
);

UPDATE HR.EMP
SET PHONE_NUMBER = 5554443322, SALARY = 20000
WHERE EMPLOYEE_ID = 250;

SELECT *
FROM HR.EMP
WHERE EMPLOYEE_ID = 250;

DELETE FROM HR.EMP
WHERE EMPLOYEE_ID = 250;

SELECT *
FROM HR.EMP;

DROP TABLE HR.EMP;