
  CREATE TABLE "SEP_INTERNS"."BALANCE" 
   (	"BAL_KEY" NUMBER NOT NULL ENABLE, 
	"PACKAGE_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PARTITION_KEY" NUMBER NOT NULL ENABLE, 
	"BEGIN_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE" DATE, 
	"USED_AMOUNT" NUMBER NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "BALANCE_PK" PRIMARY KEY ("PACKAGE_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "PACKAGE_ID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SEP_INTERNS"."PACKAGES" ("PACKAGE_ID") ENABLE, 
	 CONSTRAINT "USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SEP_INTERNS"."USERS" ("USER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

