
  CREATE TABLE "SEP_INTERNS"."PACKAGES" 
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PACKAGE_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PACKAGE_LIMIT" NUMBER NOT NULL ENABLE, 
	"BUSINESS_ZONE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"VISIBILITY" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "PACKAGES_PK" PRIMARY KEY ("PACKAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

